config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: :show

  get '/forecast' => 'static_pages#forecast'
  get '/demo' => 'static_pages#demo'

  resources :spots do
    namespace :conditions do
      resources :swells, only: %i[new create destroy]
      resources :winds, only: %i[new create destroy]
      resources :tides, except: %i[show]
    end
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user

  has_one :tide, class_name: 'Condition::Tide', dependent: :delete
  has_many :swells, class_name: 'Condition::Swell', dependent: :delete_all
  has_many :winds, class_name: 'Condition::Wind', dependent: :delete_all

  validates_presence_of :user
  validates_presence_of :name

  before_validation :trim_attributes

  def self.wave_attribute_options
    {
      break_type: %w[beach point reef],
      direction: %w[left right],
      length: %w[short average long],
      shape: %w[crumbling steep hollow],
      speed: %w[slow average fast]
    }
  end

  def slug
    name.downcase.tr(' ', '-').tr("'", '')
  end

  def to_param
    "#{id}-#{slug.parameterize}"
  end

  private

  def trim_attributes
    wave_break_type.reject!(&:blank?)
    wave_shape.reject!(&:blank?)
    wave_direction.reject!(&:blank?)
    wave_length.reject!(&:blank?)
    wave_speed.reject!(&:blank?)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, only: %i[show edit update destroy]
  respond_to :html, :js

  def index
    @spots = current_user.spots.all
    @spots_map = @spots.map do |s|
      spot = s.attributes
      spot['path'] = spot_path(s)
      spot
    end
  end

  def new
    @spot = Spot.new
    respond_with { |f| f.js { render 'new', layout: false } }
  end

  def create
    @spot = current_user.spots.create(spot_params)
    if @spot.valid?
      flash[:success] = "#{@spot.name} was successfully added to your spots"
      respond_with { |f| f.js { render 'show', layout: false } }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @spot.decorate
  end

  def edit
    respond_with { |f| f.js { render 'edit', layout: false } }
  end

  def update
    @spot.update_attributes(spot_params)
    if @spot.valid?
      flash[:success] = "#{@spot.name} was successfully updated"
      respond_with { |f| f.js { render 'show', layout: false } }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @spot.destroy
    redirect_to spots_path
  end

  private

  def spot_params
    params.require(:spot).permit(
      :name,
      :latitude,
      :longitude,
      wave_break_type: [],
      wave_shape: [],
      wave_length: [],
      wave_speed: [],
      wave_direction: []
    )
  end

  def set_spot
    @spot = current_user.spots.find_by_id(params[:id])
    return render_404 if @spot.blank? || @spot.user != current_user
  end

  def render_404
    render file: 'public/404.html', status: :not_found, layout: false
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_edit.html.slim
h2.major
  | update #{ @spot.name }s details

= simple_form_for(@spot, remote: true, html: { method: :put, class: 'check_label_form' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name

    #spot_new_map.map
    = f.input :latitude
    = f.input :longitude

    = f.input :wave_break_type,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:break_type]

    = f.input :wave_direction,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:direction]

    = f.input :wave_length,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:length]

    = f.input :wave_shape,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:shape]

    = f.input :wave_speed,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:speed]

  .form-actions
    = f.button :submit, "Update Spot"
    = f.button :button, 'Reset', type: :reset

app/views/spots/_new.html.slim
h2.major
  | Spot details

= simple_form_for(@spot, remote: true, html: { class: 'check_label_form' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name

    #spot_new_map.map
    = f.input :latitude
    = f.input :longitude

    = f.input :wave_break_type,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:break_type]

    = f.input :wave_direction,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:direction]

    = f.input :wave_length,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:length]

    = f.input :wave_shape,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:shape]

    = f.input :wave_speed,
      as: :check_boxes,
      collection: Spot.wave_attribute_options[:speed]

  .form-actions
    = f.button :submit, "Create Spot"
    = f.button :button, 'Reset', type: :reset

app/views/spots/edit.js.slim
|
  $.ajax().done(function(){
    open_modal("#{ j render "edit" }");
    initSpotNewMap();
  });

app/views/spots/index.html.slim
- provide :head_tags do
  script
    |
      document.addEventListener("turbolinks:load", function(){
        initSpotIndexMap(#{ @spots_map.to_json.html_safe });
      });

.row
  .columns.small-8
    #spot_index_map.map

  .columns.small-4

    .spots_index_header.row.align-middle
      h2.columns. Spots
      = link_to 'Add new spot', new_spot_path, class: 'columns new_spot_btn', remote: true

    - @spots.each do |spot|
      ul.spot-list
        li.row.align-bottom
          h2
            = link_to spot.name, spot_path(spot)

app/views/spots/index.slim
- provide :head_tags do
  script
    |
      document.addEventListener("turbolinks:load", function(){
        #{ spots_lat_lng = @spots.map { |s| [s.latitude, s.longitude] } }
        initSpotIndexMap(#{ spots_lat_lng.to_json.html_safe });
      });

.row
  .columns.small-8
    #spot_index_map.map

  .columns.small-4

    .spots_index_header.row.align-middle
      h2.columns. Spots
      = link_to 'Add new spot', new_spot_path, class: 'columns new_spot_btn', remote: true

    - @spots.each do |spot|
      ul.spot-list
        li.row.align-bottom
          h2
            = link_to spot.name, spot_path(spot)

app/views/spots/new.js.slim
|
  $.ajax().done(function(){
    open_modal("#{ j render "new" }");
    initSpotNewMap();
  });

app/views/spots/show.html.slim
- provide :head_tags do
  script
    |
      document.addEventListener("turbolinks:load", function(){
        initSpotShowMap(#{ @spot.latitude }, #{ @spot.longitude });
      });

#spot-show
  .row
    .columns.small-6
      #spot_show_map.map

    .columns.small-6.spot_info
      .row
        h1.columns = @spot.name
        = link_to 'Edit', edit_spot_path(@spot), class: 'columns edit_spot_btn', remote: true
        = link_to "Delete", spot_path(@spot), method: :delete, data: { confirm: { text: "Are you sure you want to delete the spot #{ @spot.name }?" } }
      ul
        li.wave_break_type
          h2 Wave Break Type
          = display_attribute(@spot.wave_break_type)

        li.wave_shape
          h2 Wave Shape
          = display_attribute(@spot.wave_shape)

        li.wave_length
          h2 Wave Length
          = display_attribute(@spot.wave_length)

        li.wave_speed
          h2 Wave Speed
          = display_attribute(@spot.wave_speed)
          
        li.wave_direction
          h2 Wave Direction
          = display_attribute(@spot.wave_direction)

  h2 Conditions

  ul(class='accordion' data-accordion data-allow-all-closed='true')
    = render 'conditions/swells/index'
    = render 'conditions/tides/index'
    = render 'conditions/winds/index'

app/views/spots/show.js.slim
|
  if("#{ flash[:success] }"){
    let content = "<h2 class='major'>Success!</h2><p>#{ flash[:success] }</p>",
        url = "#{ spot_path(@spot) }";
    open_modal(content, close_modal_and_redirect(url));
  };

app/views/spots/show.slim
#spot-show
  .row
    .columns.small-6
      = image_tag 'map-show.png'

    .columns.small-6.spot
      .row
        h1.columns = @spot.name
        = link_to 'Edit', edit_spot_path(@spot), class: 'columns edit_spot_btn', remote: true
        = link_to "Delete", spot_path(@spot), method: :delete, data: { confirm: { text: "Are you sure you want to delete the spot #{ @spot.name }?" } }
      ul
        li
          h2 Wave Break Type
          ul
            - @spot.wave_break_type.each do |x|
              li
                p = x
        li
          h2 Wave Shape
          ul
            - @spot.wave_shape.each do |x|
              li
                p = x
        li
          h2 Wave Length
          ul
            - @spot.wave_length.each do |x|
              li
                p = x
        li
          h2 Wave Speed
          ul
            - @spot.wave_speed.each do |x|
              li
                p = x
        li
          h2 Wave Direction
          ul
            - @spot.wave_direction.each do |x|
              li
                p = x

  h2 Conditions

  ul(class='accordion' data-accordion data-allow-all-closed='true')
    = render 'conditions/swells/show'
    = render 'conditions/tides/show'
    = render 'conditions/winds/show'


javascript:

  $(document).on('turbolinks:load', function() {
    if("#{ flash[:notice]}"){
      let content = "<h2 class='major'>Success!</h2><p>#{ flash.now[:success] }</p>"
      $('.modal_content').html(content).promise().done(function(){
        $('#modal').foundation('open');
      });
      setTimeout(function() {
        $('#modal').foundation('close').html('');
      }, 2000);
    }
  })