config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: :show

  get '/forecast' => 'static_pages#forecast'
  get '/demo' => 'static_pages#demo'

  resources :spots do
    namespace :conditions do
      resources :swells, only: %i[new create destroy]
      resources :winds, only: %i[new create destroy]
      resources :tides, except: %i[show]
    end
  end
end

app/models/condition.rb
module Condition
  def self.table_name_prefix
    'condition_'
  end

  def self.direction_options
    %w[N NE E SE S SW W NW]
  end
end

app/models/condition/swell.rb
module Condition
  class Swell < ApplicationRecord
    belongs_to :spot

    validates :rating, presence: true
    validates :min_height, presence: true
    validates :min_period, presence: true

    before_validation :remove_nil_values_from_arrays

    private

    def remove_nil_values_from_arrays
      direction.reject!(&:blank?)
    end
  end
end

app/models/condition/tide.rb
module Condition
  class Tide < ApplicationRecord
    belongs_to :spot
    before_validation :remove_nil_values_from_arrays

    validates :size, presence: true

    def self.position_offset_options
      [['1st', 1], ['2nd', 2], ['3rd', 3], ['4th', 4], ['5th', 5], ['6th', 6]]
    end

    def self.size_options
      [['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10], ['11', 11]]
    end

    private

    def remove_nil_values_from_arrays
      rising.reject!(&:blank?)
      dropping.reject!(&:blank?)
      size.reject!(&:blank?)
    end
  end
end

app/models/condition/wind.rb
module Condition
  class Wind < ApplicationRecord
    belongs_to :spot

    before_validation :remove_nil_values_from_arrays

    validates :direction, presence: true
    validates :max_speed, presence: true
    validates :rating, presence: true

    def self.name_options
      %w[onshore crossshore offshore]
    end

    private

    def remove_nil_values_from_arrays
      direction.reject!(&:blank?)
      name.reject!(&:blank?)
    end
  end
end

app/models/forecast/tide.rb
module Forecast
  class Tide
    attr_reader :day, :data, :high, :low, :size

    def initialize(day, data)
      @day = day
      @data = data
      @high = get_tides(data, 'high')
      @low = get_tides(data, 'low')
      @size = set_tide_size
    end

    private

    def set_tide_size
      height = (high.first[:height] + high.last[:height]) / 2
      if height < 7
        return 'small'
      elsif height < 8.5
        return 'average'
      elsif height < 9.5
        return 'big'
      else
        return 'massive'
      end
    end

    def get_tides(data, type)
      tides = data.select { |t| t['type'] == type }
      tides.map { |t| { time: t['time'], height: t['height'].round(2) } }
    end
  end
end

app/controllers/conditions/swell_controller.rb
class Conditions::SwellController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, only: [:new, :create]
  before_action :set_condition, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js

  def new
    @swell = @spot.swell_conditions.new
    respond_with { |f| f.js { render 'new', layout: false } }
  end

  def create
    @swell = @spot.swell_conditions.create(swell_params)
    if @swell.valid?
      flash[:success] = "Successfully added new swell conditions to #{ @swell.spot.name }"
      redirect_to(spot_path(@swell.spot))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @swell.update_attributes(swell_params)
      redirect_to(spot_condition_path(@condition.spot, @condition))
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @swell.destroy
    redirect_to spot_path(@swell.spot)
  end

private

  def swell_params
    params.require(:condition_swell).permit(
      :rating,
      :min_height,
      :max_height,
      :min_period,
      direction: []
    )
  end

  def set_spot
    @spot = current_user.spots.find_by_id(params[:spot_id])
    if @spot.blank? || @spot.user != current_user
      return render_404_template
    end
  end

  def set_condition
    @condition = Condition::Condition.find_by_id(params[:id])
    if @condition.blank? || @condition.spot.user != current_user
      return render_404_template
    end
  end

  def render_404_template
    render file: 'public/404.html', status: :not_found, layout: false
  end
end

app/controllers/conditions/swells_controller.rb
module Conditions
  class SwellsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_spot
    before_action :set_swell, only: :destroy

    respond_to :html, :js

    def new
      @swell = @spot.swells.new
      respond_with { |f| f.js { render 'new', layout: false } }
    end

    def create
      @swell = @spot.swells.create(swell_params)
      if @swell.valid?
        flash[:success] = "Successfully added Swell conditions to #{@swell.spot.name}"
        respond_with { |f| f.js { render 'spots/show', layout: false } }
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @swell.destroy
      flash[:success] = "Successfully deleted Swell conditions from #{@swell.spot.name}"
      respond_with { |f| f.js { render 'spots/show', layout: false } }
    end

    private

    def swell_params
      params.require(:condition_swell).permit(
        :rating,
        :min_height,
        :max_height,
        :min_period,
        direction: []
      )
    end

    def set_spot
      @spot = current_user.spots.find_by_id(params[:spot_id])
      return render_404 if @spot.blank? || @spot.user != current_user
    end

    def set_swell
      @swell = Condition::Swell.find_by_id(params[:id])
      return render_404 if @swell.blank? || @swell.spot.user != current_user
    end

    def render_404
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/conditions/tides_controller.rb
module Conditions
  class TidesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_spot
    before_action :set_tide, only: %i[edit update destroy]

    respond_to :html, :js

    def new
      @tide = @spot.build_tide
      respond_with { |f| f.js { render 'new', layout: false } }
    end

    def create
      @tide = @spot.create_tide(tide_params)
      if @tide.valid?
        flash[:success] = "Successfully added Tide conditions to #{@tide.spot.name}"
        respond_with { |f| f.js { render 'spots/show', layout: false } }
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      respond_with { |f| f.js { render 'edit', layout: false } }
    end

    def update
      @tide.update_attributes(tide_params)
      if @tide.valid?
        flash[:success] = 'Tide conditions were successfully updated'
        respond_with { |f| f.js { render 'spots/show', layout: false } }
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @tide.destroy
      flash[:success] = "Successfully deleted Swell conditions from #{@tide.spot.name}"
      respond_with { |f| f.js { render 'spots/show', layout: false } }
    end

    private

    def tide_params
      params.require(:condition_tide).permit(
        rising: [],
        dropping: [],
        size: []
      )
    end

    def set_spot
      @spot = current_user.spots.find_by_id(params[:spot_id])
      return render_404 if @spot.blank? || @spot.user != current_user
    end

    def set_tide
      @tide = @spot.tide
      return render_404 if @tide.blank? || @tide.spot.user != current_user
    end

    def render_404
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/conditions/winds_controller.rb
module Conditions
  class WindsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_spot
    before_action :set_wind, only: :destroy

    respond_to :html, :js

    def index
      respond_with { |f| f.js { render 'index', layout: false } }
    end

    def new
      @wind = @spot.winds.new
      respond_with { |f| f.js { render 'new', layout: false } }
    end

    def create
      @wind = @spot.winds.create(wind_params)
      if @wind.valid?
        flash[:success] = "Successfully added Wind conditions to #{@wind.spot.name}"
        respond_with { |f| f.js { render 'spots/show', layout: false } }
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @wind.destroy
      flash[:success] = "Successfully deleted Wind conditions from #{@wind.spot.name}"
      respond_with { |f| f.js { render 'spots/show', layout: false } }
    end

    private

    def wind_params
      params.require(:condition_wind).permit(
        :rating, :max_speed, name: [], direction: []
      )
    end

    def set_spot
      @spot = current_user.spots.find_by_id(params[:spot_id])
      return render_404 if @spot.blank? || @spot.user != current_user
    end

    def set_wind
      @wind = Condition::Wind.find_by_id(params[:id])
      return render_404 if @wind.blank? || @wind.spot.user != current_user
    end

    def render_404
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/views/conditions/tides/_edit.html.slim
h2.major
  | Tide Conditions
= simple_form_for(@tide, url: spot_conditions_tide_path(@spot.id, @spot.tide), remote: true, html: { method: :put, class: 'check_label_form' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :rising,
      as: :check_boxes,
      collection: Condition::Tide.position_offset_options,
      label: 'Position (rising tide times)'

    = f.input :dropping,
      as: :check_boxes,
      collection: Condition::Tide.position_offset_options,
      label: 'Position (dropping tide times)'

    = f.input :size,
      as: :check_boxes,
      collection: Condition::Tide.size_options

  .form-actions
    = f.button :submit, "Update Conditions"
    = button_tag 'Reset', type: :reset, class: 'button'

app/views/conditions/tides/_index.html.slim
li(class='accordion-item' data-accordion-item)
  a(id='accordion-tides' class='accordion-title' href='#') Tide
  div(class='accordion-content' data-tab-content)

    - if @spot.tide.nil?
      = link_to 'Add new conditions',
        new_spot_conditions_tide_path(@spot),
        class: 'columns new_tide_btn',
        remote: true
    - else
      ul id="spot_tide"
        li Rising tide offset surf times
        = display_tide_offset_values('rising')

        li Dropping tide offset surf times
        = display_tide_offset_values('dropping')

        li Sizes
        - @spot.tide.size.each do |value|
          = "#{ value } "

        = link_to 'Edit',
          edit_spot_conditions_tide_path(@spot, @spot.tide),
          class: 'columns delete_condition',
          remote: true

        = link_to 'Delete',
          spot_conditions_tide_path(@spot, @spot.tide),
          method: :delete,
          class: 'columns delete_condition',
          remote: true,
          data: { confirm: { text: "Are you sure you want to delete the tide conditions?" } }

app/views/conditions/tides/_new.html.slim
h2.major
  | Tide Conditions

= simple_form_for(@tide, url: spot_conditions_tides_path(@spot.id), remote: true, html: { class: 'check_label_form' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :rising,
      as: :check_boxes,
      collection: Condition::Tide.position_offset_options,
      label: 'Position (rising tide times)',
      error: "Rising tide times can't be blank"

    = f.input :dropping,
      as: :check_boxes,
      collection: Condition::Tide.position_offset_options,
      label: 'Position (dropping tide times)',
      error: "Dropping tide times can't be blank"

    = f.input :size,
      as: :check_boxes,
      collection: Condition::Tide.size_options

  .form-actions
    = f.button :submit, "Add Conditions"
    = button_tag 'Reset', type: :reset, class: 'button'

app/views/conditions/tides/edit.js.slim
|
  $.ajax().done(function(){
    open_modal("#{ j render "edit" }");
  });

app/views/conditions/tides/new.js.slim
|
  $.ajax().done(function(){
    open_modal("#{ j render "new" }");
  });