config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: :show

  get '/forecast' => 'static_pages#forecast'
  get '/demo' => 'static_pages#demo'

  resources :spots do
    namespace :conditions do
      resources :swells, only: %i[new create destroy]
      resources :winds, only: %i[new create destroy]
      resources :tides, except: %i[show]
    end
  end
end

app/views/layouts/_demo_navigation.html.slim
nav
  ul.menu.primary-nav.menu-hover-lines.user-navigation.flex-container.align-center
    li
      = link_to 'Home', root_path
    li.forecast
      = link_to 'Forecast', forecast_path
    li.spots
      = link_to 'Spots', spots_path
    li
      = link_to 'Sign Up', new_user_registration_path

app/views/layouts/_primary_navigation.html.slim
nav
  ul.menu.menu-hover-lines.user-navigation.flex-container.align-center
    li
      = link_to 'Demo', demo_path
    li
      = link_to 'Sign Up', new_user_registration_path
    li
      = link_to 'Log In', new_user_session_path

app/views/layouts/_user_navigation.html.slim
nav
  ul.menu.primary-nav.menu-hover-lines.user-navigation.flex-container.align-center
    li.forecast
      = link_to 'Forecast', forecast_path
    li.spots
      = link_to 'Spots', spots_path
    li.users
      = link_to 'Dashboard', user_path(current_user)
    li
      = link_to 'Sign Out', destroy_user_session_path, method: :delete, id: 'sign_out'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    / <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    title Surfable
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+ENV['GOOGLE_MAPS_KEY']
    = yield(:head_tags)
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    article(id='modal' class='reveal'
      data-animation_speed=10000
      data-reveal
      data-v-offset='0'
      data-animation-in="slide-in-down fast"
      data-animation-out='slide-out-up fast')
      button(class="close-button" aria-label="Close alert" type="button" data-close)
        span(aria-hidden='true') &times;
      .modal_content

    body(id="#{body_id}")
      p.notice= notice
      p.alert= alert

      div.wrapper
        header
          div.primary-nav.flex-container.flex-dir-column
            header
              = image_tag "logo.png", class: 'logo'
              
              - if user_signed_in?
                - if current_user.demo
                  = render 'layouts/demo_navigation'
                - else
                  = render 'layouts/user_navigation'
              - else
                = render 'layouts/primary_navigation'

        div.main-content
          = yield

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Saltydog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    body.is-preload
      p.notice= notice
      p.alert= alert
      - if user_signed_in?
        = link_to 'Sign Out', destroy_user_session_path, method: :delete, id: 'sign_out'
        = link_to 'Dashboard', user_path(current_user)
        = link_to 'Spots', spots_path

      = yield